## Numpy

In [1]:
import numpy as np

NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in scientific computing, data analysis, and machine learning due to its high performance and ease of use.

Key features of NumPy include:

- **ndarray**: A powerful N-dimensional array object which is the core of the NumPy library.
- **Mathematical functions**: Comprehensive mathematical functions to operate on arrays and matrices.
- **Linear algebra**: Tools for performing linear algebra operations.
- **Random number generation**: Functions for generating random numbers.
- **Integration with other libraries**: Compatibility with other scientific computing libraries like SciPy, Pandas, and Matplotlib.

Here's an example of using NumPy to create an array and perform basic operations:

```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Perform basic operations
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
```

Output:

```
Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
```

## Creating arrays (1D, 2D, & 3D)

In [26]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

In [27]:
arr.shape

(5,)

In [28]:
arr.ndim

1

In [13]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr_2d)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
#1st 3 is the number of rows, and the last"3" is the number of columns
arr_2d.shape

(3, 3)

In [30]:
arr_2d.ndim

2

In [16]:
# Create a 3D array
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])
print("3D Array:\n", arr_3d)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [21]:
#1st "3" is the number of matrices, 2nd "2" is the number of rows in each matrix, while the last "3" is the number of columns in the matrices
arr_3d.shape

(3, 2, 3)

In [22]:
arr_3d.ndim

3

## Accessing a single element in the different dimensions

In [17]:
# Accessing a single element
print("Element at (1, 0, 2):", arr_3d[1, 0, 2])  # Output: 9

# Accessing a 2D sub-array (a "slice" of the 3D array)
print("2D slice at index 0:\n", arr_3d[0])  # Output: [[1 2 3] [4 5 6]]

# Accessing a row across all layers
print("First row across all layers:\n", arr_3d[:, 0, :])  # Output: [[ 1  2  3] [ 7  8  9] [13 14 15]]

# Slicing
print("Sub-array:\n", arr_3d[1:, :, 1:3])

Element at (1, 0, 2): 9
2D slice at index 0:
 [[1 2 3]
 [4 5 6]]
First row across all layers:
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
Sub-array:
 [[[ 8  9]
  [11 12]]

 [[14 15]
  [17 18]]]


In [14]:
# Accessing a single element
print("Element at (0, 1):", arr_2d[0, 1])  # Output: 2

# Accessing a row
print("First row:", arr_2d[0])  # Output: [1 2 3]

# Accessing a column
print("First column:", arr_2d[:, 0])  # Output: [1 4 7]

# Slicing
print("Sub-array:\n", arr_2d[0:2, 1:3])

Element at (0, 1): 2
First row: [1 2 3]
First column: [1 4 7]
Sub-array:
 [[2 3]
 [5 6]]


In [18]:
# Element-wise addition
arr_2d_2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
sum_2d = arr_2d + arr_2d_2
print("Element-wise Sum of 2D Arrays:\n", sum_2d)

# Matrix multiplication
matrix_mult_2d = np.dot(arr_2d, arr_2d_2.T)
print("Matrix Multiplication of 2D Arrays:\n", matrix_mult_2d)

Element-wise Sum of 2D Arrays:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Matrix Multiplication of 2D Arrays:
 [[ 68  86 104]
 [167 212 257]
 [266 338 410]]


In [19]:
# Element-wise addition
arr_3d_2 = np.array([
    [[10, 11, 12], [13, 14, 15]],
    [[16, 17, 18], [19, 20, 21]],
    [[22, 23, 24], [25, 26, 27]]
])
sum_3d = arr_3d + arr_3d_2
print("Element-wise Sum of 3D Arrays:\n", sum_3d)

# Summing along an axis
sum_along_axis = np.sum(arr_3d, axis=0)
print("Sum along axis 0:\n", sum_along_axis)

Element-wise Sum of 3D Arrays:
 [[[11 13 15]
  [17 19 21]]

 [[23 25 27]
  [29 31 33]]

 [[35 37 39]
  [41 43 45]]]
Sum along axis 0:
 [[21 24 27]
 [30 33 36]]


In [3]:
# Perform basic operations
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


In [6]:
import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create an array of zeros
zeros = np.zeros((3, 3))

# Create an array of ones
ones = np.ones((2, 4))

# Create an array with a range of values
range_array = np.arange(10, 20)

# Create an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)

print("1D Array:", arr1)
print("2D Array:\n", arr2)
print("Zeros Array:\n", zeros)
print("Ones Array:\n", ones)
print("Range Array:", range_array)
print("Linspace Array:", linspace_array)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range Array: [10 11 12 13 14 15 16 17 18 19]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [7]:
# Element-wise operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Add 5:", arr + 5)
print("Multiply by 2:", arr * 2)

# Mathematical functions
print("Square Root:", np.sqrt(arr))
print("Logarithm:", np.log(arr))

# Aggregate functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

Original Array: [10 20 30 40]
Add 5: [15 25 35 45]
Multiply by 2: [20 40 60 80]
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532]
Logarithm: [2.30258509 2.99573227 3.40119738 3.68887945]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing
print("Element at index 2:", arr[2])

# Slicing
print("Elements from index 2 to 5:", arr[2:6])
print("Elements from start to index 3:", arr[:4])
print("Elements from index 4 to end:", arr[4:])
print("Every second element:", arr[::2])

Element at index 2: 3
Elements from index 2 to 5: [3 4 5 6]
Elements from start to index 3: [1 2 3 4]
Elements from index 4 to end: [5 6 7 8 9]
Every second element: [1 3 5 7 9]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reshape
reshaped = arr.reshape((1, 9))
print("Reshaped Array:\n", reshaped)

# Transpose
transposed = arr.T
print("Transposed Array:\n", transposed)

Reshaped Array:
 [[1 2 3 4 5 6 7 8 9]]
Transposed Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))

Minimum: 1
Maximum: 9
Median: 5.0
Variance: 6.666666666666667


In [11]:
# Random integers between 0 and 10
random_ints = np.random.randint(0, 10, size=5)

# Random floats between 0 and 1
random_floats = np.random.random(size=5)

# Normally distributed random numbers
normal_dist = np.random.normal(loc=0, scale=1, size=5)

print("Random Integers:", random_ints)
print("Random Floats:", random_floats)
print("Normally Distributed Random Numbers:", normal_dist)

Random Integers: [7 1 4 5 5]
Random Floats: [0.60090906 0.82038451 0.85250323 0.06615651 0.80623237]
Normally Distributed Random Numbers: [ 0.04388763  0.7555332  -0.16400168  1.01281475 -2.54065459]


In [12]:
# Dot product of two vectors
a = np.array([1, 2])
b = np.array([3, 4])
dot_product = np.dot(a, b)
print("Dot Product:", dot_product)

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(A, B)
print("Matrix Product:\n", matrix_product)

# Determinant of a matrix
determinant = np.linalg.det(A)
print("Determinant:", determinant)

# Inverse of a matrix
inverse = np.linalg.inv(A)
print("Inverse:\n", inverse)

Dot Product: 11
Matrix Product:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
